### ISSUE TITLE
JSBin examples not working

### ISSUE THREAD

**Issue by bernardoadc** [getify/asynquence#113]
```
"error"
"ReferenceError: ASQ is not defined
    at qutabu.js:56:1"
```

**Comment by getify** [comment]
Fixed, thanks.

**Comment by bernardoadc** [comment]
I'm still getting it here.

Sorry, maybe i'm not so clear. I've tried these 2 links:
- https://jsbin.com/luron/1/edit?js,console,output
- https://jsbin.com/qutabu/1/edit?js,console,output

Both give me in console that ASQ is not defined. And I can't "add library" since asynquence is not there.

**Comment by getify** [comment]
Sorry, I fixed the jsbin code itself, but didn't realize I needed to update the links. The READMEs now have corrected links.
